In [16]:
import numpy as np
import cv2

In [17]:
# Load an color image in grayscale
img = cv2.imread('test.png',0) 
print(img)

[[168 168 167 ... 171 177 154]
 [168 167 167 ... 174 182 158]
 [169 166 167 ... 150 132  99]
 ...
 [ 59  61  64 ...  82  98 102]
 [ 56  61  61 ...  95 110 111]
 [ 53  61  59 ... 106 116 118]]


In [18]:
f = open("test_case.txt", "a")
f_1 = open("result_python.txt", "a")
def convolve2D(image, kernel, padding=0, strides=2):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [19]:
x, y = img.shape
for _x in range(x):
    for _y in range(y):
        f.write(np.binary_repr(img[_x, _y], width=16) + '\n')
f.close()
kernel = np.array([[-1, 0, 1],
                   [-2, 0, 2],
                   [-1, 0, 1]])
result = convolve2D(img, kernel)
x, y = result.shape
for _x_1 in range(x):
    for _y_1 in range(y):
        f_1.write(np.binary_repr(int(result[_x_1, _y_1]), width=16) + '\n')
f_1.close()
print(img[0][0], img[0][1], img[0][2])
print(img[1][0], img[1][1], img[1][2])
print(img[2][0], img[2][1], img[2][2])
print(result[0][0])

168 168 167
168 167 167
169 166 167
5.0


In [20]:
cv2.imshow('image',img)
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()